### ISSUE TITLE
Doesnt work with build from outside the source directory

### ISSUE THREAD

**Issue by danners** [ggreer/jekyll-gallery-generator#18]
Hey,
im trying to use jekyll-gallery-generator for a project.
It works fine if i serve jekyll from the source folder with jekyll serve.
But i have a push to deploy setup that runs jekyll build from out of the source directory.

If i do this, it fails to find the correct files, something with the paths is messed up. 
I tried to fix it, but i couldn't make it work, the paths and dirs etc were a little bit confusing.

In the failing example there is a photos directory in the source dir, but it fails to find it since it uses the currentpath of the running jekyll executable to look for it.
Here is the failure:

simon@simon-laptop ~/code % jekyll build -V -s blog2 -d blog_fertig
Configuration file: blog2/_config.yml
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
            Source: blog2
       Destination: blog_fertig
      Generating... 
Error generating galleries: No such file or directory @ dir_initialize - photos
/home/simon/code/blog2/_plugins/jekyll-gallery-generator.rb:213:in `open'
/home/simon/code/blog2/_plugins/jekyll-gallery-generator.rb:213:in `foreach'
/home/simon/code/blog2/_plugins/jekyll-gallery-generator.rb:213:in `generate'
/home/simon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:280:in `block in generate'
/home/simon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:279:in `each'
/home/simon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:279:in `generate'
/home/simon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:50:in `process'
/home/simon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
/home/simon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
/home/simon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
/home/simon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
/home/simon/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
/home/simon/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
/home/simon/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
/home/simon/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
/home/simon/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
/home/simon/.gem/ruby/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
/home/simon/.gem/ruby/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
/home/simon/.gem/ruby/2.2.0/bin//jekyll:23:in `load'
/home/simon/.gem/ruby/2.2.0/bin//jekyll:23:in `<main>'
                    done.
 Auto-regeneration: disabled. Use --watch to enable.

**Comment by ggreer** [comment]
Please try the latest version (0.0.6).

**Comment by danners** [comment]
Works as expected now, thanks a lot.
