### ISSUE TITLE
Image textual info

### ISSUE THREAD

**Issue by sowdust** [ggreer/jekyll-gallery-generator#27]
Is it possible to somehow add some text description to each image? Maybe a YAML file to be named after the image file?

**Comment by ggreer** [comment]
More YAML seems like the wrong way to go about it. EXIF allows metadata such as a description field. I might add an option to show that info.

**Comment by ggreer** [comment]
I've exposed EXIF data. You should be able to get descriptions with `{{ image.exif.comment }}`.
