### ISSUE TITLE
_config.yml settings not considered when folder name is a number

### ISSUE THREAD

**Issue by joaomvfsantos** [ggreer/jekyll-gallery-generator#35]
Let's say I have a folder called "2017" inside the photos folder with the following _config.yml configuration:

```yml
gallery:
    galleries:
        2017:
            name: "Two Thousand Seventeen"
            info:
                desc: "These are photos from 2017"
```

Although the 2017 gallery is displayed it shows "2017" as name when it should display "Two Thousand Seventeen".

**Comment by ggreer** [comment]
If the folder name is "2017", shouldn't `test:` be changed to `"2017":`?

**Comment by joaomvfsantos** [comment]
You are absolutely right. This was a typo, I already updated it.
