### ISSUE TITLE
Error generating thumbs

### ISSUE THREAD

**Issue by CesarDenis** [ggreer/jekyll-gallery-generator#36]
When the plugin is generating the thumbs this error appears:

`Error reading EXIF data for galeria-de-fotos/edicao46/photo_0001.jpg: uninitialized constant EXIFR::JPEG`

Can you help me?
Thank you

**Comment by moroz** [comment]
I get the same error. Please change the requirements in main file to:
```ruby
require 'exifr/jpeg'
require 'rmagick'
include Magick
```
This fixes the error for me.

**Comment by CesarDenis** [comment]
Tks @moroz fixes for me to.
