### ISSUE TITLE
Request to sort photos by name/date, either in a given album, or by default

### ISSUE THREAD

**Issue by ycaniou** [ggreer/jekyll-gallery-generator#5]
Hi,

Could you improve the plugin so that we can configure the creation of the thumbnails, sorted by name/date/? instead of date? This could maybe be done either globally of by album, with a keyword like "sort:" in the "galleries:" sections, or upper for the default one.
Cheers.

**Comment by ggreer** [comment]
I used two different cameras on a recent trip, so I finally needed this feature. The latest version of this plugin sorts images in galleries by date. If there's no date, it falls back to sorting by filename.
